name: Build & Release

# This will trigger the workflow for any tag that starts with 'v'
on:
  push:
    tags:
      - 'v*'

# Allows the workflow to create release
permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: windows-latest
    steps:
    - name: Sync Repo to the Server
      uses: actions/checkout@v1

    - name: Compile 64bit Binary
      run: |
        windres version.rc -o version.o
        gcc .\src\bin_grabber.c version.o -o .\output\bin_grabber_x64.exe -s -m64

    - name: Remove Placeholder
      run: Remove-Item output/.gitkeep

    - name: Get tag name
      run: echo "Tag name is ${GITHUB_REF#refs/tags/}"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${GITHUB_REF#refs/tags/}
        name: BinGrabber ${GITHUB_REF#refs/tags/}
        make_latest: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: ./output/*
