name: Build, Test & Release

# Sets the trigger to changing the VERSION file in the main branch
on:
  push:
    branches:
    - main
    paths:
    - 'VERSION'

# Allows the workflow to create release
permissions:
  contents: write

jobs:
  build_test_and_release:
    runs-on: windows-latest
    steps:
    - name: Sync Repo to the Server
      uses: actions/checkout@v1

    - name: Compile 64bit Binary
      run: |
        windres version.rc -o version.o
        gcc .\src\bin_grabber.c version.o -o .\output\bin_grabber_x64.exe -s -m64

    - name: Test the Tool
      run: |
        .\output\bin_grabber_x64.exe running_processes
        $output = Get-ChildItem running_processes
        if (-not ($output | Where-Object -FilterScript {$_.Name -eq "processes.csv"})) {
          Write-Output "Didn't found processes.csv"
          exit 1
        }

    - name: Remove Placeholder
      run: Remove-Item output/.gitkeep

    - name: Read Version
      run: |
        $version = Get-Content VERSION
        Write-Output "VERSION=$version" >> $env:GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: BinGrabber ${{ env.VERSION }}
        make_latest: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: ./output/*
